lab7/config/routes.rb
Rails.application.routes.draw do
  resources :microposts
  resources :users # this was created when I generated a scaffold around 'User'

  get 'newhome/page1'
  get 'newhome/page2'
  get '/singlepage', to: 'single#singlepage'
  get '/', to: 'root#homepage'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # these were manually added
  get '/home/page1' # home#page1... '/home/' was created in part_6.1
  get '/home/page2' # home#page2
end

lab7/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lab7/app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
end

lab7/app/models/person.rb
class Person < ApplicationRecord
  validates :name, presence: true # this requires that each instance of Person has a name
end

lab7/app/models/user.rb
# this is the model for the 'User Table'.. this file was create when I generated a scaffold for user
class User < ApplicationRecord
  has_many(:micropost, dependent: :destroy)

  # has_many is a function call that corrects the "ConstraintException: FOREIGN KEY constraint failed" error
  # I think the error here occured because I tried to delete a user and the microposts were a 'child' of the user and we were not deleting them as well...to fix this we need to delete the microposts for the user that we are deleting!
  # what this function does is destroy the 'Microposts' for a user when the user is deleted
end

lab7/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base; end

lab7/app/controllers/home_controller.rb
# note: this was implemented when I was adding the rails routes/pages manually

class HomeController < ApplicationController # rails will get view: page1.html.erb
  def page1; end
  def page2; end # rails will get view: page2.html.erb
end

lab7/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

lab7/app/controllers/newhome_controller.rb
class NewhomeController < ApplicationController
  def page1
    @time = Time.now
  end

  def page2
    @time2 = Time.now
  end
end

lab7/app/controllers/root_controller.rb
class RootController < ApplicationController
  def homepage; end
end

lab7/app/controllers/single_controller.rb
class SingleController < ApplicationController
  def singlepage; end
end

lab7/app/controllers/users_controller.rb
# NOTE: this file and code was created when I generated a scaffold around 'User'

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html do
          redirect_to @user, notice: 'User was successfully created.'
        end
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html do
          redirect_to @user, notice: 'User was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html do
        redirect_to users_url, notice: 'User was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

lab7/app/helpers/application_helper.rb
module ApplicationHelper; end

lab7/app/helpers/microposts_helper.rb
module MicropostsHelper
end

lab7/app/helpers/new_helper.rb
module NewHelper
end

lab7/app/helpers/newhome_helper.rb
module NewhomeHelper
end

lab7/app/helpers/users_helper.rb
module UsersHelper
end

lab7/app/views/home/page1.html.erb
<h1>Hello this is msg is from 'page1.html.erb'!</h1>
<p><i>note: this was done in part_6.1</i></p>

lab7/app/views/home/page2.html.erb
<h1>Hello this is msg is from 'page2.html.erb'!</h1>
<p><i>note: this was done in part_6.1</i></p>

lab7/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Myrailsapp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <h1>My first rails app</h1>
  <h4>This is written in the 'application.html.erb' FILE which is in the layouts foulder!</h4>
  <%# this yield will output the html on page1.html.erb and page2.html.erb %>
  <%= yield %>
</body>

</html>

lab7/app/views/microposts/_form.html.erb
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

lab7/app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

lab7/app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Microposts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td><%= micropost.content %></td>
        <td><%= micropost.user_id %></td>
        <td><%= link_to 'Show', micropost %></td>
        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Micropost', new_micropost_path %>

lab7/app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Back', microposts_path %>

lab7/app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>

lab7/app/views/newhome/_footer.html.erb
<br>
<p>--------------------------------------------------------------------------------------</p>
<p>Copyright <%= "#{start_year}" if defined? start_year %> - <%= Date.today.year %>MyCode</p>
<p><i>note: everythign from the line down is the footer</i></p>
<p>Hello Just trying something new again w/ git</p>

lab7/app/views/newhome/page1.html.erb
<h1>Newhome#page1</h1>
<p>Find me in app/views/newhome/page1.html.erb</p>
<h1>Hello this is msg is from 'page1.html.erb'!</h1>
<p>it is <%= @time %> now</p>
<%# <a href ="./page2">page2</a> %>
<%# there is a better way for me to link to page2... done below %>
<%= link_to "page2", newhome_page2_path %>
<%= render partial: "footer", locals: {start_year: 2012} %>
<p><i>note: this was done in part_6.2</i></p>

lab7/app/views/newhome/page2.html.erb
<h1>Newhome#page2</h1>
<p>Find me in app/views/newhome/page2.html.erb</p>
<h1>Hello this is msg is from 'page2.html.erb'!</h1>
<p>It is <%= @time2 %> now on page 2</p>
<%# <a href ="./page1">page2</a> %>
<%# there is a better way for me to link to page1... done below %>
<%= link_to "page1", newhome_page1_path %>
<%# partial files are use a "_" before the name of the file %>
<%= render partial: "footer", locals: {start_year: 2021} %>
<p><i>note: this was done in part_6.2</i></p>

lab7/app/views/root/homepage.html.erb
<h1>Welcome to the homepage.. which is in the root foulder under views</h1>
<p><i>note: this was done in part_6.2</i></p>

lab7/app/views/single/singlepage.html.erb
<h1>single page</h1>
<p><i>note: this was done in part_6.2</i></p>

lab7/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

lab7/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

lab7/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Users</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.id %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New User', new_user_path %>

lab7/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

lab7/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>ID:</strong>
  <%= @user.id %>
</p>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>